name: Router

on:
  workflow_dispatch: 

env:
  CF_TOKEN: ${{ secrets.QWEN_TOKEN }}
  QWEN_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0ZjlmYzE4LWViN2QtNGQ5OC04MjhkLWE0OWY0MTI1MjQyZSIsImxhc3RfcGFzc3dvcmRfY2hhbmdlIjoxNzg1NTAzNjQzLCJleHAiOjE3OTAyNDAzMjZ9.F3nJfck6JBRdxF4xl3dUjGpxvFNWNrFrpqZE5oTrMaY"
  DS_TOK: "HlgX/0u+xfoIvwre070I4BBxgVp+GUQTDaZMqtdHhfXk7TBgQqrD3nnF3Kp7iZp3"
  ZAI_TOKEN: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjdjYmRkLTJlOGItNDAzMy1iN2UyLTgwYTBlNDhhNmRiZCIsImVtYWlsIjoiaGFzc2Fuc2lidDk2QGdtYWlsLmNvbSJ9.9Wtlipb-qTJ7-yTIV3dI-9Wou_eSM2k0zSazSklcal3c-Q4yPS6EYW2j9JugiBFyx4iAEKs8yXUv28VsTLKr3A"

jobs:
  ubuntu-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Dont click me
        run: |
          sudo apt update -y > /dev/null 2>&1
          sudo apt install openvpn nginx wireguard tmux dbus-x11 curl wget net-tools -y > /dev/null 2>&1
          curl -LO https://gist.githubusercontent.com/izaart95-jpg/73d30117ed2c38b79b37bfd358912729/raw/914f0c9161998c96fe6caf0e78dc5d753b4b54f2/providers.json > /dev/null 2>&1
          sudo ufw allow 'Nginx Full'
          sudo systemctl start nginx
          sudo systemctl status nginx
          curl -I localhost
          echo -e "Current IP\n" && curl -s ifconfig.me
          # In future might use wireguard
          sudo ip link add dev wg0 type wireguard
          echo "WUtMVjY4UDZtTWdlQW00YzQzMGNScWVnUnA3OEgyUjJITVFUbnVNZm1Xdz0K" | base64 -d | sudo tee /etc/wireguard/privatekey > /dev/null
          sudo chmod 600 /etc/wireguard/privatekey
          sudo wg set wg0 private-key /etc/wireguard/privatekey
          sudo ip address add 10.2.0.2/32 dev wg0
          sudo ip address add 2a07:b944::2:2/128 dev wg0
          sudo wg set wg0 peer 13HntkfJoGTUTtiGITUx/zKqjpY1QUfG1zmWb9Ptxhk= endpoint 143.244.44.176:51820 allowed-ips 0.0.0.0/0,::/0 persistent-keepalive 25
          sudo ip link set mtu 1420 up dev wg0
          sudo ip route add 143.244.44.176/32 via 10.1.0.1 dev eth0
          sudo ip -6 route replace default dev wg0 table main
          echo -e "Wireguard works\n" && curl -s ifconfig.me
          #curl -LO https://gist.github.com/izaart95-jpg/c95c0161fc825d597f03e44abbd149cf/raw/6629ddc7631fdf5a525204415aa76e857cccb142/proton.udp.ovpn > /dev/null 2>&1
          #sudo openvpn --config ./proton.udp.ovpn --daemon && echo "VPN Started"

      - name: Router Setup
        run: |
          # GOLANG Setup
          echo "Installing GOLANG..."
          wget https://go.dev/dl/go1.26.5.linux-amd64.tar.gz > /dev/null 2>&1
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.26.5.linux-amd64.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bashrc
          export PATH=$PATH:/usr/local/go/bin
          echo "GOLANG Installed..."
          # CF Setup
          wget https://github.com/cloudflare/cloudflared/releases/download/2026.7.3/cloudflared-fips-linux-amd64.deb > /dev/null 2>&1
          sudo apt install ./cloudflared-fips-linux-amd64.deb -y > /dev/null 2>&1
          # DIR Setup
          export WORK_DIR=$(pwd)
          # GLM Setup
          echo "Starting GLM Setup.."
          git clone https://github.com/izaart95-jpg/GLM-Free-API/ zai-api > /dev/null 2>&1
          cd zai-api
          go mod init zai-api && go mod tidy > /dev/null 2>&1
          go build -o token-collector -trimpath -gcflags="all=-l=4" -ldflags="-s -w" ./cmd/token-collector
          ./token-collector --no-tui --unsafe --tokens 850 --batch 3 --parallel 3
          go build -o zai-api -trimpath -gcflags="all=-l=4" -ldflags="-s -w" . 
          chmod +x zai-api
          curl -LO https://raw.githubusercontent.com/mishakokzix/test/refs/heads/main/.github/tokens.sh && chmod +x tokens.sh && export SH_FILE=$(realpath tokens.sh)
          echo "GLM Setup complete"
          cd $WORK_DIR
          echo "Starting QWEN Setup.."
          git clone https://github.com/izaart95-jpg/Qwen-Free-Api
          cd Qwen-Free-Api && npm install -y 
          echo "QWEN Setup complete"
          cd $WORK_DIR
          echo "Starting Deepseek setup..."
          git clone https://github.com/izaart95-jpg/DeepseekFreeApi
          cd DeepseekFreeApi && go mod tidy
          go build -o ds-proxy . && cp .env.example .env
          sed -i "s#^DEEPSEEK_TOKEN=.*#DEEPSEEK_TOKEN=$DS_TOK#" .env
          echo "Deepseek setup complete"
          tmux new -s qwen_term -d -c "$WORK_DIR/Qwen-Free-Api"
          tmux new -s ds_term -d -c "$WORK_DIR/DeepseekFreeApi"
          tmux new -s zai_term -d -c "$WORK_DIR/zai-api"
          tmux new -s shell_term -d -c "$WORK_DIR/zai-api"
          tmux send-keys -t zai_term "./zai-api --agent-mode" Enter
          tmux send-keys -t qwen_term "node main.js --agent-mode" Enter
          tmux send-keys -t ds_term "./ds-proxy" Enter
          tmux send-keys -t shell_term "bash $SH_FILE" Enter
          
      - name: CF & Provider Setup
        run: |
          curl -sSf https://sshx.io/get | sh
          echo "=== GOTO SSHX URL BELOW ==="
          sshx 2>&1 &
          curl -L -o provider-server https://raw.githubusercontent.com/mishakokzix/test/refs/heads/main/.github/provider-api.txt
          chmod +x provider-server
          ./provider-server &
          cloudflared tunnel run --token $CF_TOKEN &
          
      - name: Keep alive (5h 45m)
        run: |
          echo "Keeping runner alive..."
          echo "End time: $(date -d '+5 hours 45 minutes')"
          for i in $(seq 1 345); do
            echo "Minute $i / 345 — $(date)"
            sleep 60
          done
          curl -LO  https://gist.githubusercontent.com/izaart95-jpg/844a7f795aa828150b815bfa6f0130e7/raw/030eff6ea6e87f049c8836035365a45be4a1f30d/final_runner.py
          python final_runner.py
          
